#Test

sudo: required # 관리자 권한 갖기

language: generic # 언어(플랫폼)을 선택

services: # 도커 환경 구성
    - docker

before_install: # 스크립트를 실행할 수 있는 파일 명시 및 이미지 다운
    - echo "start Creating an image with dockerfile"
    - docker build -t yonghyeon/docker-react-app -f Dockerfile.dev ./

script: # 실행할 스크립트(테스트 실행)
    - docker run -e CI=true yonghyeon/docker-react-app npm run test -- --coverage

after_success:
    - echo "Test Success"

# 배포
deploy:
    edge: true
    provider: elasticbeanstalk # 외부 서비스 표시(s3, elasticbeanstalk, firebase 등등)
    region: "ap-northeast-2" # 현재 사용하고 있는 AWS의 서비스가 위치하고 있는 물리적 장소
    app: "docker-react-app" # 생성된 어플레키이션 이름
    env: "Docker-react-app-env" # 환경의 이름
    bucket_name: "elasticbeanstalk-ap-northeast-2-989988856674" # 해당 elasticbeanstalk을 위한 s3 버켓 이름
    bucket_path: "docker-react-app"
    on:
        branch: main

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
